#!/usr/bin/env python3
"""
twitter-pull onboarding wizard
Guides you through setup in ~2 minutes. Run: python onboard.py
"""
from __future__ import annotations
import os
import sys
import subprocess
from pathlib import Path
import yaml

ROOT = Path(__file__).parent

PRESETS = {
    "ai_news":      "AI News          — model releases, research, industry moves",
    "ai_building":  "Building with AI — coding tools, RAG, agents, tutorials",
    "startups":     "Startups & VC    — funding rounds, YC, founder insights",
    "tech_news":    "Tech News        — big tech, open source, developer tools",
    "crypto":       "Crypto & Web3    — DeFi, protocols, regulation",
    "news":         "World News       — breaking news, major world events",
    "science":      "Science          — research papers, biotech, climate",
    "geopolitics":  "Geopolitics      — policy, international relations",
}

DEFAULT_ACCOUNTS = [
    ("sama",           "Sam Altman (OpenAI)"),
    ("karpathy",       "Andrej Karpathy"),
    ("ylecun",         "Yann LeCun"),
    ("elonmusk",       "Elon Musk"),
    ("paulg",          "Paul Graham"),
    ("balajis",        "Balaji Srinivasan"),
    ("benedictevans",  "Benedict Evans"),
    ("swyx",           "swyx — AI engineering"),
    ("goodside",       "Riley Goodside — prompting"),
    ("emollick",       "Ethan Mollick — Wharton AI"),
]

def hr(): print("─" * 60)
def heading(s): hr(); print(f"  {s}"); hr()

def ask(prompt: str, default: str = "") -> str:
    hint = f" [{default}]" if default else ""
    val = input(f"{prompt}{hint}: ").strip()
    return val or default

def ask_yn(prompt: str, default: bool = True) -> bool:
    hint = "Y/n" if default else "y/N"
    val = input(f"{prompt} [{hint}]: ").strip().lower()
    if not val:
        return default
    return val.startswith("y")

def pick_from_list(items: list[tuple[str, str]], prompt: str, defaults: list[str]) -> list[str]:
    """Numbered multi-select. Returns list of keys."""
    print(f"\n{prompt}")
    print("  Enter numbers separated by spaces, or 'all', or press Enter for defaults.\n")
    keys = [k for k, _ in items]
    for i, (key, desc) in enumerate(items, 1):
        marker = "*" if key in defaults else " "
        print(f"  [{marker}] {i:2}. {desc}")
    print(f"\n  (* = default)")
    raw = input("\n  Your choices: ").strip()
    if not raw:
        return defaults
    if raw.lower() == "all":
        return keys
    selected = []
    for part in raw.split():
        try:
            idx = int(part) - 1
            if 0 <= idx < len(keys):
                selected.append(keys[idx])
        except ValueError:
            if part in keys:
                selected.append(part)
    return selected or defaults


def write_env(getxapi_key: str, anthropic_key: str) -> None:
    env_path = ROOT / ".env"
    lines = ["# twitter-pull API keys\n"]
    lines.append(f"GETXAPI_KEY={getxapi_key}\n")
    if anthropic_key:
        lines.append(f"ANTHROPIC_API_KEY={anthropic_key}\n")
    env_path.write_text("".join(lines))
    print(f"  Written: .env")


def write_feed(accounts: list[str], presets: list[str], obsidian_dir: str) -> None:
    feed_path = ROOT / "config" / "feed.yaml"

    # build yaml manually to preserve comments
    acct_lines = "\n".join(f"  - {a}" for a in accounts)
    preset_lines = "\n".join(f"  - {p}" for p in presets)
    obsidian_line = (
        f'  obsidian_dir: "{obsidian_dir}"'
        if obsidian_dir
        else '  # obsidian_dir: "~/Documents/YourVault/Twitter Digests"'
    )

    content = f"""\
# ─────────────────────────────────────────────────────────────────────────────
# YOUR PERSONAL FEED  (generated by onboard.py — edit freely)
# Run `python main.py --dry-run` to test changes.
# ─────────────────────────────────────────────────────────────────────────────

accounts:
{acct_lines}

presets:
{preset_lines}

# Add your own topics below. No query syntax needed.
# custom_topics:
#   - name: "Robotics"
#     any: ["robotics", "humanoid robot", "Boston Dynamics"]
#     min_likes: 20
custom_topics: []

output:
  digest_dir: "digests"
  keep_days: 30
{obsidian_line}
"""
    feed_path.write_text(content)
    print(f"  Written: config/feed.yaml")


def run_test() -> bool:
    print("\n  Running a quick test (1 preset, 10 tweets)…")
    result = subprocess.run(
        ["uv", "run", "python", "main.py", "--dry-run", "--presets", "ai_news", "--topics-only"],
        capture_output=True, text=True, cwd=ROOT
    )
    if result.returncode == 0:
        lines = result.stdout.strip().splitlines()
        # show first 10 lines of output
        preview = "\n".join(lines[:10])
        print(f"\n  ✓ Working! Preview:\n\n{preview}\n  …")
        return True
    else:
        print(f"\n  ✗ Something went wrong:\n{result.stderr[-800:]}")
        return False


def install_cron(hour_utc_1: int, hour_utc_2: int) -> None:
    log = str(ROOT / "logs" / "cron.log")
    (ROOT / "logs").mkdir(exist_ok=True)

    # Use `uv run` so no venv activation needed and deps are always in sync
    def cron_line(h): return f"0 {h} * * * cd {ROOT} && uv run python main.py >> {log} 2>&1"

    import subprocess
    existing = subprocess.run(["crontab", "-l"], capture_output=True, text=True).stdout
    cleaned = "\n".join(l for l in existing.splitlines() if "twitter-pull" not in l)
    new_crontab = cleaned.rstrip() + f"\n{cron_line(hour_utc_1)}\n{cron_line(hour_utc_2)}\n"
    subprocess.run(["crontab", "-"], input=new_crontab, text=True, check=True)
    print(f"  Cron installed: {hour_utc_1:02d}:00 UTC and {hour_utc_2:02d}:00 UTC daily")


def main():
    print("\n" + "═" * 60)
    print("  twitter-pull setup wizard")
    print("═" * 60)
    print("\nThis takes about 2 minutes.\n")

    # ── API keys ────────────────────────────────────────────────────────────
    heading("Step 1 of 4 — API Keys")

    existing_env = (ROOT / ".env").exists()
    if existing_env:
        print("  .env already exists.")
        if not ask_yn("  Overwrite?", default=False):
            print("  Keeping existing .env.")
            getxapi_key = ""
            anthropic_key = ""
        else:
            existing_env = False

    if not existing_env:
        print("\n  GetXAPI key — get free credits at https://getxapi.com")
        print("  (~$1.50/month for typical personal use)")
        getxapi_key = ask("  GETXAPI_KEY")

        print("\n  Anthropic key — for AI summaries (optional)")
        print("  Without it, digests show top tweets ranked by engagement.")
        print("  Get one at https://console.anthropic.com")
        anthropic_key = ask("  ANTHROPIC_API_KEY (press Enter to skip)")

        write_env(getxapi_key, anthropic_key)

    # ── topic presets ───────────────────────────────────────────────────────
    heading("Step 2 of 4 — Topics")

    chosen_presets = pick_from_list(
        list(PRESETS.items()),
        "Which topics do you want in your daily digest?",
        defaults=["ai_news", "ai_building", "startups"],
    )
    print(f"\n  Selected: {', '.join(chosen_presets)}")

    # ── accounts ────────────────────────────────────────────────────────────
    heading("Step 3 of 4 — Accounts to Follow")

    chosen_accounts = pick_from_list(
        DEFAULT_ACCOUNTS,
        "Which accounts should be included? (their tweets are summarized together)",
        defaults=[u for u, _ in DEFAULT_ACCOUNTS],
    )

    print("\n  Add more accounts? Enter usernames separated by spaces (or press Enter to skip).")
    extra = input("  Extra accounts: ").strip()
    if extra:
        chosen_accounts.extend(extra.split())

    print(f"\n  Following {len(chosen_accounts)} accounts.")

    # ── Obsidian ────────────────────────────────────────────────────────────
    obsidian_dir = ""
    if ask_yn("\n  Sync digests to an Obsidian vault?", default=False):
        obsidian_dir = ask("  Vault path (e.g. ~/Documents/MyVault/Twitter Digests)")

    write_feed(chosen_accounts, chosen_presets, obsidian_dir)

    # ── test ────────────────────────────────────────────────────────────────
    heading("Step 4 of 4 — Test Run")

    if ask_yn("  Run a quick test fetch now?", default=True):
        ok = run_test()
        if not ok:
            print("\n  Fix the error above, then re-run: python onboard.py")
            sys.exit(1)

    # ── cron ────────────────────────────────────────────────────────────────
    print()
    if ask_yn("  Install daily cron job?", default=True):
        print("\n  Digests will run twice a day. Enter your timezone offset from UTC.")
        print("  Examples: San Francisco (PDT) = -7, London (BST) = +1, Tokyo = +9")
        try:
            offset = int(ask("  UTC offset", default="0"))
        except ValueError:
            offset = 0
        # 6am and 12pm local → UTC
        h1 = (6 - offset) % 24
        h2 = (12 - offset) % 24
        try:
            install_cron(h1, h2)
        except Exception as e:
            print(f"  Could not install cron automatically: {e}")
            print(f"  Add these lines manually with `crontab -e`:")
            print(f"    0 {h1} * * * cd {ROOT} && .venv/bin/python main.py >> logs/cron.log 2>&1")
            print(f"    0 {h2} * * * cd {ROOT} && .venv/bin/python main.py >> logs/cron.log 2>&1")

    # ── done ────────────────────────────────────────────────────────────────
    hr()
    print("\n  All done! Your digest will run automatically.")
    print("\n  Useful commands:")
    print("    python main.py --dry-run       # preview without writing")
    print("    python main.py                 # run now and write digest")
    print("    cat config/feed.yaml           # view/edit your feed")
    print("    ls digests/                    # view past digests")
    print()


if __name__ == "__main__":
    main()
